### ISSUE TITLE
Verbo 'GET' não está passando as propriedades no parametro da requisição

### ISSUE THREAD

**Issue by leonardodelfino** [thrust-bitcodes/http-client#3]
Ao realizar uma chamada utilizando o http-cliente, se utilizarmos o verbo POST conforme o código a baixo, ao capturar a chamada no servidor podemos observar que a propriedade que foi setada está chegando corretamente:

**Requisição utilizando POST:**
```
let resultado = httpClient.post(URL_THRUST + '/app/autenticacao/verificaUsuarioLogado', {})
        .property('cookie', cookiesSessao)
        .fetch()    
```
**Print do request no servidor:** 
` {  ... 
    "cookie": "JSESSIONIDSSO=4zSHvq8IUgMxXOTODHfJYWDvuW_laDk3YaVrydoU; path=/" 
...  }`

**Requisição utilizando GET:**
```
let resultado = httpClient.get(URL_THRUST + '/app/autenticacao/verificaUsuarioLogado')
        .property('cookie', cookiesSessao)
        .fetch()    
```

**Print do request no servidor:** 
` {  ... 
    "cookie": null
...  }`

Ao analisar o código do biticode http-client, notei que na **linha 81** são adicionado os properties, mas dentro de um IF apenas para os verbos POST E PUT. Os verbos restantes não está sendo adicionado as propriedades do cabeçalho da requisição.

Este problema está impactando o desenvolvimento dos testes para as rotas que necessitam serem consumidas via GET.

**Comment by cneryjr** [comment]
Bitcode corrigido!
Obrigado pela contribuição!
