### ISSUE TITLE
Problema com parametros do verbo GET

### ISSUE THREAD

**Issue by leonardodelfino** [thrust-bitcodes/http-client#4]
Boa Tarde,

Após a última atualização estamos tendo um problema com a passagem de parametros no verbo get:

Para o código abaixo escrito dentro de um arquivo `/app/teste.js` :

```
  params: function (params, req, res) {
    res.json(params)
  },

  testarParams: function (params, req, res) {
    var resp = httpClient.get('http://localhost:8778/app/teste/params?id=557897').fetch()
    res.json(resp.body)
  }
```

Se abrir a url **http://localhost:8778/app/teste/params?id=557897** através do browser, obtemos o resultado:
```
{
"id": 557897
}
```

Ao chamar a mesma URL através do httpClient, (criamos o exemplo, está na rota **http://localhost:8778/app/teste/testarParams**) obtemos o seguinte resultado:
```
{
"id": "557897?"
}

Antes da atualização o resultado era o mesmo, após a atualização o dado esta sendo enviado no formato errado, string ao invés de number e está sendo devolvido um ponto de interrogação no final.
```

**Comment by Brunomachadob** [comment]
Conforme mostrado nos exemplos, criei o arquivo:

```javascript
//test.js
var httpClient = require('http-client');

exports = {
  params: function (params, req, res) {
    res.json(params)
  },

  testarParams: function (params, req, res) {
    var resp = httpClient.get('http://localhost:8778/app/test/params?id=557897').fetch()
    res.json(resp.body)
  }
}
```
Através do postman e do chrome, realizei ambas as chamadas.
O erro não foi apresentado em nenhum dos ambientes e chamadas.

Favor verificar a versão do http-client utilizada e se acontecerá com você na última versão.
Caso simulado, reabrir a issue com os detalhes de simulação

Imagens do postman abaixo:

![test1](https://user-images.githubusercontent.com/4688763/40387010-aaafdbf0-5de1-11e8-90c9-68af44f64904.png)

![test2](https://user-images.githubusercontent.com/4688763/40387016-ae24719c-5de1-11e8-8ff0-7e9bec7fa262.png)
