### ISSUE TITLE
Erro ao realizar POST

### ISSUE THREAD

**Issue by eciojunior** [thrust-bitcodes/http-client#5]
Fiz uns testes em uma API, realizando um POST passando um JSON e alguns Headers. Porém nao esta me retornando nada, e se jogar em um Try Catch,  aparece um erro de Java. Quando realizo a mesma requisição via POSTMAN, o retorno no body é vazio e o código e 403 (este código é o esperado, mapeado pela API). 

Fiz um debug no thrust e verifiquei que a httpConection no método getContent está chegando undefined.

Qualquer dúvida estou a disposição.

**Comment by eciojunior** [comment]
Esse problema aconteceu pq nao contém body no retorno. Então esta alteração resolveu meu problema.

```
    getErrorContent: function(httpConnection) {
      try {
        var inputStream = httpConnection.getErrorStream()
        var scanner = new Scanner(inputStream, 'UTF-8')
        var content = scanner.useDelimiter('\\Z|\\A').next()

        scanner.close()
        inputStream.close()

        return content
      } catch (error) {
        return {}
      }
    },
```

**Comment by Brunomachadob** [comment]
O problema foi ajustado.
Disponível na release [1.3.3](https://github.com/thrust-bitcodes/http-client/releases/tag/1.3.3)
